/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    colors: {
      gold: {
        50: 'rgb(var(--accent-soft) / <alpha-value>)',
        100: 'rgb(var(--accent-soft) / <alpha-value>)',
        200: 'rgb(var(--accent) / 0.72)',
        300: 'rgb(var(--accent) / 0.86)',
        400: 'rgb(var(--accent) / <alpha-value>)',
        500: 'rgb(var(--accent) / 0.9)',
        600: 'rgb(var(--accent) / 0.78)',
        700: 'rgb(var(--accent) / 0.68)',
        800: 'rgb(var(--accent) / 0.58)',
        900: 'rgb(var(--accent) / 0.48)',
      },
      background: 'rgb(var(--bg) / <alpha-value>)',
      surface: 'rgb(var(--surface) / <alpha-value>)',
      card: 'rgb(var(--card) / <alpha-value>)',
      border: 'rgb(var(--border) / <alpha-value>)',
      foreground: 'rgb(var(--text) / <alpha-value>)',
      muted: 'rgb(var(--text-muted) / <alpha-value>)',
      accent: 'rgb(var(--accent) / <alpha-value>)',
      success: 'rgb(var(--success) / <alpha-value>)',
      warning: 'rgb(var(--warning) / <alpha-value>)',
      danger: 'rgb(var(--danger) / <alpha-value>)',
      sidebar: 'rgb(var(--sidebar-bg) / <alpha-value>)',
      'sidebar-foreground': 'rgb(var(--sidebar-text) / <alpha-value>)',
      slate: {
        50: 'rgb(var(--text) / 0.98)',
        100: 'rgb(var(--text) / 0.94)',
        200: 'rgb(var(--text) / 0.86)',
        300: 'rgb(var(--text) / 0.76)',
        400: 'rgb(var(--text-muted) / 1)',
        500: 'rgb(var(--text-muted) / 0.82)',
        600: 'rgb(var(--text-muted) / 0.68)',
        700: 'rgb(var(--border) / 0.9)',
        800: 'rgb(var(--border) / 0.72)',
        900: 'rgb(var(--surface) / 0.92)',
        950: 'rgb(var(--bg) / 1)',
      },
      amber: {
        300: 'rgb(var(--warning) / 0.86)',
        400: 'rgb(var(--warning) / 1)',
        500: 'rgb(var(--warning) / 1)',
        600: 'rgb(var(--warning) / 0.86)',
        950: 'rgb(var(--warning) / 0.16)',
      },
      emerald: {
        300: 'rgb(var(--success) / 0.86)',
        400: 'rgb(var(--success) / 1)',
        500: 'rgb(var(--success) / 1)',
        950: 'rgb(var(--success) / 0.16)',
      },
      rose: {
        300: 'rgb(var(--danger) / 0.86)',
        400: 'rgb(var(--danger) / 1)',
        500: 'rgb(var(--danger) / 1)',
        950: 'rgb(var(--danger) / 0.16)',
      },
      red: {
        200: 'rgb(var(--danger) / 0.76)',
        300: 'rgb(var(--danger) / 0.86)',
        400: 'rgb(var(--danger) / 1)',
        500: 'rgb(var(--danger) / 1)',
        950: 'rgb(var(--danger) / 0.16)',
      },
      sky: {
        300: 'rgb(var(--accent) / 0.86)',
        400: 'rgb(var(--accent) / 1)',
        500: 'rgb(var(--accent) / 1)',
      },
      cyan: {
        300: 'rgb(var(--success) / 0.86)',
        400: 'rgb(var(--success) / 1)',
        500: 'rgb(var(--success) / 1)',
        600: 'rgb(var(--success) / 0.86)',
        950: 'rgb(var(--success) / 0.16)',
      },
      blue: {
        600: 'rgb(var(--accent) / 0.86)',
      },
      purple: {
        400: 'rgb(var(--accent) / 1)',
        500: 'rgb(var(--accent) / 1)',
      },
    },
    extend: {
      fontFamily: {
        serif: ['Playfair Display', 'Georgia', 'serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
